apiVersion: v1
kind: Service
metadata:
  name: opencode-master-orchestrator
  namespace: opencode-system
  labels:
    app: opencode-master
    component: orchestrator
spec:
  selector:
    app: opencode-master
    component: orchestrator
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: opencode-slave-agents
  namespace: opencode-system
  labels:
    app: opencode-slave
    component: agent
spec:
  selector:
    app: opencode-slave
    component: agent
  ports:
    - name: agent-port
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: opencode-redis
  namespace: opencode-system
  labels:
    app: opencode-redis
spec:
  selector:
    app: opencode-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: opencode-postgres
  namespace: opencode-system
  labels:
    app: opencode-postgres
spec:
  selector:
    app: opencode-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
